server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: halo:8848 # nacos地址
      discovery:
        cluster-name: HZ
        namespace: 45e30304-1b64-4c21-8c83-22309949af10 # 命名空间，填ID
    gateway:
      routes: # 网关路由配置
        - id: user-service-gateway # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: order-service-gateway
          uri: lb://order-service
          predicates:
            - Path=/order/**
            - Before=2037-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: # 默认过滤项
        - AddRequestHeader=Truth, Halo
