server:
  port: 8081
spring:
  application:
    name: user-service # 服务名称
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_user?useSSL=false
    username: root
    password: mogu2018
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: halo:8848
      discovery:
        cluster-name: HZ # 集群名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
